# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias ll='ls -alF'
export PS1='\n\[\e[7;36m\][$(date +%H:%M)] \u@\h \w\[\e[0m\]\n $ '

# EXPORT CACHE
export EEN_CACHE_DIR='/var/lib/een/cache'
export EEN_ELASTICSEARH_CACHE_DIR='/var/lib/een-elasticsearch/cache'
export EEN_API_CACHE_DIR='/var/lib/een-api/cache'
